### ISSUE TITLE
I just made Polish translation for this app!

### ISSUE THREAD

**Issue by BadOmen94PL** [truefedex/tv-bro#103]
Hello - I just did Polish translation - i dont have a access to pull, so i added my file here - to @truefedex please make folder strings pl and add this file - change txt to XML. I hope Polish version of this app will be soon! Thanks!
[strings.txt](https://github.com/truefedex/tv-bro/files/8758371/strings.txt)

**Comment by MailYouLater** [comment]
Hello @BartoszHnat,
I'm not sure why you pinged me... or most of the other people you @mentioned in the above comment for that matter...
Anyway, it would be pretty weird if you did have access to pull or push directly to this repository since as far as I can tell, you've never been involved with it previously.

The best way to get started submitting changes to someone's project on GitHub is to:
1. ["Fork"](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) the project ([which I see you have done](https://github.com/BadOmen94PL/tv-bro))
2. Make the changes in your fork (preferably on [a new branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository#creating-a-branch)).
3. [Submit a pull request from that branch on your fork to the original project](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

Also, I noticed that you didn't translate "Settings" or "System" ... Is this intentional? did these just get missed? or do Polish speakers prefer to use the English words for these?

I looked at the Polish translations of a couple of other open source projects, and saw that "Settings" and "Options" were translated as "Ustawienia" and "Opcje" respectively, would one of these possibly be better than simply leaving the English "Settings" in place?

I did also look for a translation for "System" too, but it seemed like the way this gets translated might depend on the context too much for me (who does not speak Polish) to be able to get it right.  I looked for something used in the same context, and the closest I could find is Firefox's "Use system colors" which is translated as "Kolory systemowe", I don't know how appropriate that is for this, or how to alter it to work better, so I'll leave it to you, or another Polish speaker.

**Comment by BadOmen94PL** [comment]
@MailYouLater ok, i forked, added folder values_pl with corections (i didnt find "options" , but "settings" corrected) where can i add supoort (when app sees android Lauange is Polish set values to PL)?

**Comment by truefedex** [comment]
@BadOmen94PL thank you for contribution. If you are not a developer and making changes on single non-code file then making fork and pull request are not necessary I think. I can check your translations manually and apply on next tv bro versions. Sorry for long not answering - I currently busy on other projects but will return to tv bro soon.
@MailYouLater thank you for support!

**Comment by BadOmen94PL** [comment]
@truefedex 

I have no patience for git hub - i used MS Visual Code and it tells me errors - its just not for my nervs. 
[strings.txt](https://github.com/truefedex/tv-bro/files/8788976/strings.txt)

I give the file here - please use it in next version.

**Comment by MailYouLater** [comment]
@BadOmen94PL So "System" just stays as "System"?  No Polish string for that?

**Comment by MailYouLater** [comment]
@BadOmen94PL I don't see the changes in your fork, but I decided to put together a PR for you.  If you pick a better translation for "System" you can post it in here or in #105 and I'll add it to the PR.

**Comment by truefedex** [comment]
Thank you @MailYouLater & @BadOmen94PL! Your changes are merged. Sorry for not answering so long (I was very busy and rarely checked email so did not notice notifications)
