### ISSUE TITLE
Incognito mode doesn't work.

### ISSUE THREAD

**Issue by Levani-mirvelashvili** [truefedex/tv-bro#88]
Hello, I tried incognito mode, but it still saves browsing history, I need incognito mode because I want streaming like mode, just browse and watch something and not store it locally, cause data collects and TV becomes unresponsive. 

I tried many times in incognito mode but history is still showing visited pages. Please fix it.

Used device: Xiaomi Mi TV Box S 4K.

**Comment by truefedex** [comment]
Do you mean history still showing visited pages after exiting incognito mode?
If you checking it during incognito mode (before exiting from it) - visited pages and all sites data are saved by design.
Only after exiting incognito mode, the data is deleted. Tha same way incognito mode working in other browsers.

**Comment by Levani-mirvelashvili** [comment]
Yes, I just checked, History isn't saved it's only temporarily stored. Thank you. Слава Україні! 🇺🇦
