### ISSUE TITLE
the best browser for android tv

### ISSUE THREAD

**Issue by nexusdiscord** [truefedex/tv-bro#9]
I just found this browser when try searching on github, its this project abandon? why this app only can be found on regular google play not tv?

**Comment by truefedex** [comment]
Hi. This project is still alive. But development are very slow. It is can not be found in play for tvs because it rejected by google admins with following reasons (quote):
"
Non-full screen static banner ads Your app displays static banner ads which are not full screen. Please refer to our Functionality documentation.
--
App links to or depends on web browser Your app relies on presentation of  web content. Android TV does not support any web browsing content. Please refer to our documentation for details. For example, your app links to web content in the settings.
"

https://developer.android.com/docs/quality-guidelines/tv-app-quality
I.e google don't want web content on Android TV platform :)

**Comment by MailYouLater** [comment]
I don't know about the part about "Non-full screen static banner ads" part, as I haven't seen any ads, at least not yet (are there ads?) but I'm pretty sure you're misinterpreting the "App links to or depends on web browser" part.

As poorly written as it is, I don't think that means that "Google do[es]n't want web content on Android TV platform", but rather that they clicked the GitHub link in the "VERSION & UPDATE" tab of TV Bro's settings and saw that it triggered an intent that would launch a browser instead of loading the page in TV Bro.  I think the reason they disallow this behaviour is because there is no browser included by default, which I realize shouldn't matter to a browser app which responds correctly to that intent, but I'm fairly certain that's the behaviour they were complaining about.  Especially considering their example.
> For example, your app links to web content in the settings.

**Comment by truefedex** [comment]
Thank you MailYouLater, I think I will change behaviour with link in settings and will load it directly in tv bro. It's a good idea.
But google indicated the same reason long before the link appeared in the settings. So it's definitely not related.
And TVBro does not and has never contained any advertisements. They are clearly hinting that ads banners is contained on the Internet itself.

**Comment by MailYouLater** [comment]
Hmmm... If you're right, then I wonder how other browsers get around these issues.  Because there are some browsers on the Android TV section of the Google Play Store.

**Comment by truefedex** [comment]
I know. Only two if Im not mistaken. Puffin (i think because he doesn't use WebView or something like that) and some old not updatable "TV Web browser" (I guess it is not banned by Google because it was published very early and has not been updated since - so it just wasn't noticed). Nevertheless there are no Firefox although it has a [version for ATV](https://github.com/mozilla-mobile/firefox-tv) nor [Opera ](https://youtu.be/qq_cdavDpWk).

**Comment by MailYouLater** [comment]
Well, I've tried Firefox TV and I'm surprised they weren't too ashamed of it to even call it Firefox.  Puffin has a decent user experience, but doesn't run fully locally, and can't download.  TV Web Browser sounds sketchy to me, has a terrible UI, and also doesn't allow downloading.  I can't find a place to download Opera for Android TV to even try it.  Downloader by AFTVnews... doesn't seem to have been designed to be used for browsing.

Unlike all of those, TV Bro has a fairly intuitive interface, runs locally, allows downloading, and being open source inspires confidence. I wish this was available on the Android TV portion of the Google Play Store so I could recommend it to people who don't know how to add APKs from other locations.
